### PR TITLE
manually select the VCF files to import variants from

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/481)

### CODE REVIEW

**Comment by woook** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[code/VCFImport/VCFImport.py, line 112 at r1](https://reviewable.io:443/reviews/woook/moka-fe/481#-L8CObF4A15V9n2X1LxX:-L8CObF4A15V9n2X1LxY:b-ic4yvj) ([raw file](https://github.com/woook/moka-fe/blob/daefb05d8267eb8815fd28a1e7a4c18f2851d794/code/VCFImport/VCFImport.py#L112)):*
> ```Python
> 		for vcfFile in self.vcfPaths.itervalues(): # for each vcf...
> 			
> 			# test if vcf is not compressed.
> ```

I think this should be split out so it's not in two places and is more object-oriented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/481)*

**Comment by woook** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[code/VCFImport/VCFImport.py, line 112 at r1](https://reviewable.io:443/reviews/woook/moka-fe/481#-L8CObF4A15V9n2X1LxX:-L8COkQRUGzyNtUPn4p1:b-n5ek5b) ([raw file](https://github.com/woook/moka-fe/blob/daefb05d8267eb8815fd28a1e7a4c18f2851d794/code/VCFImport/VCFImport.py#L112)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

I think this should be split out so it's not in two places and is more object-oriented.
</blockquote></details>

PS - I think it's fine to store the decompressed VCF

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/481)*

**Comment by woook** [comment]
+@woook 

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/481#-:-L8CP6mj8nWCkAHnIAF_:b20ih3)*

**Comment by aledj2** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[code/VCFImport/VCFImport.py, line 112 at r1](https://reviewable.io:443/reviews/woook/moka-fe/481#-L8CObF4A15V9n2X1LxX:-L8Dd__yMuZCOMW_3PSV:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/daefb05d8267eb8815fd28a1e7a4c18f2851d794/code/VCFImport/VCFImport.py#L112)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

PS - I think it's fine to store the decompressed VCF
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/481)*

**Comment by woook** [comment]
Has this been tested?
Not for now, but one day it would be nice if the code for s0901 & s0902 were modularised, to be OOP

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[forms/s0901_WESTestResults, line 391 at r2](https://reviewable.io:443/reviews/woook/moka-fe/481#-L8cTafxK4RQQtmkJGZr:-L8cTafxK4RQQtmkJGZs:b-95k5yn) ([raw file](https://github.com/woook/moka-fe/blob/0ebcacc7ad072add0085dc9dbfbd5f7c6a5367bd/forms/s0901_WESTestResults#L391)):*
> ```
>             ' append the
>             csFileLst = csFileLst & vcfDict(strKey)
>             If loopcount <> vcfDict.count Then 'If not the last file in list
> ```

`<>`
should that be `<` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/481#-:-L8cV7_ff_U_zYecusFs:b-zihgqr)*

**Comment by aledj2** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[forms/s0901_WESTestResults, line 391 at r2](https://beta.reviewable.io/reviews/woook/moka-fe/481#-L8cTafxK4RQQtmkJGZr:-L8gSJTuE2zwZ-ZJmzST:b-22tyl1) ([raw file](https://github.com/woook/moka-fe/blob/0ebcacc7ad072add0085dc9dbfbd5f7c6a5367bd/forms/s0901_WESTestResults#L391)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

`<>`
should that be `<` ?

</blockquote></details>

I think either will work. (I borrowed this code from somewhere else)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/481)*

**Comment by aledj2** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[forms/s0901_WESTestResults, line 391 at r2](https://beta.reviewable.io/reviews/woook/moka-fe/481#-L8cTafxK4RQQtmkJGZr:-L8gT_095UxN7D-ghr0r:b-ut164v) ([raw file](https://github.com/woook/moka-fe/blob/0ebcacc7ad072add0085dc9dbfbd5f7c6a5367bd/forms/s0901_WESTestResults#L391)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I think either will work. (I borrowed this code from somewhere else)
</blockquote></details>

I haven't changed this sorry as I ran out of time to test it. If the Moka release can wait til Thursday PM will do it then

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/481)*

**Comment by woook** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/481#-:-L8m6DGuCbrAH0XUYLtb:bnfp4nl)*

**Pull request merged**
