### PR TITLE
Primerdatabase requirements doc

### PR DESCRIPTION
**Pull request by aledj2**
Has been approved by Matt and Sue

---
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/365)

### CODE REVIEW

**Comment by aledj2** [comment]
changes have been made in line with architecture review on 21st Nov with @aledj2 and @woook

**Comment by andyb3** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[code/PrimerDB/ImportPrimer.py, line 77 at r1](https://reviewable.io:443/reviews/woook/moka-fe/365#-KzdQWKF1jOzzbcLPIYK:-KzdQWKF1jOzzbcLPIYL:b-1bvzj7) ([raw file](https://github.com/woook/moka-fe/blob/985a30b98a6f652ca9a18e5ff1d37d72c9b967a5/code/PrimerDB/ImportPrimer.py#L77)):*
> ```Python
> 							
> 							# create a dict of all variables to be inserted to the database and pass to self.build_insert module
> 							primer_values_to_insert_dict = {"chr" : str(chromosome_lookup) , "start" : str(primer_start) , "stop" : str(primer_stop) ,
> ```

FYI according to PEP8 you're not meant to be have whitespace immediately before a comma or colon, just a single whitsepace after. See https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements

---

*[code/PrimerDB/ImportPrimer.py, line 120 at r1](https://reviewable.io:443/reviews/woook/moka-fe/365#-KzdTfu8b3EXsOu89xnS:-KzdTfu9SQZEEmRGXBMC:bkztga8) ([raw file](https://github.com/woook/moka-fe/blob/985a30b98a6f652ca9a18e5ff1d37d72c9b967a5/code/PrimerDB/ImportPrimer.py#L120)):*
> ```Python
> 				
> 		# build sql insert statement
> 		insert_query = 'insert into dbo.PrimerAmplicon ("ForwardSeq","ReverseSeq","ChromosomeID","Start19","Stop19","Status","FTagName","FTagSequence","FTagOrderingName","RTagName",\
> ```

FYI Doesn't really matter but I don't think you need to put the field names in quotes in an SQL statement do you? Again doesn't really matter but couldn't you just use double quotes for the values rather than backslash escaped single quotes? I think that might make it look slightly neater, avoids having to have strings like `'\',\'' \` on the line below

---

*[code/PrimerDB/ImportPrimerConfig.py, line 2 at r1](https://reviewable.io:443/reviews/woook/moka-fe/365#-KzdXdKXT2TQ3yjWhbr0:-KzdXdKXT2TQ3yjWhbr1:b-246as6) ([raw file](https://github.com/woook/moka-fe/blob/985a30b98a6f652ca9a18e5ff1d37d72c9b967a5/code/PrimerDB/ImportPrimerConfig.py#L2)):*
> ```Python
> # location of primer design files to import
> primer_design_files = "\\\\gstt.local\\shared\\Genetics\\DNA LAB\\Primers\\MokaPrimerDatabase\\primer_designs"
> ```

FYI I think you could also just add r in front of the string to avoid having to escape every backslash i.e. `r"\\gstt.local\shared\Genetics\DNA LAB\Primers\MokaPrimerDatabase\primer_designs"`

---

*[forms/61001_PrimerDB_dashboard, line 58 at r1](https://reviewable.io:443/reviews/woook/moka-fe/365#-KzdZHU6fx6rOWGh9oeq:-KzdZHU6fx6rOWGh9oer:b-59x1hh) ([raw file](https://github.com/woook/moka-fe/blob/985a30b98a6f652ca9a18e5ff1d37d72c9b967a5/forms/61001_PrimerDB_dashboard#L58)):*
> ```
>     DoCmd.OpenForm stDocName, , , stLinkCriteria
>     
>     'open form which displays all primers awating ordering
> ```

The comment here and below say 'open form' but the command below is actually closing the form.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/365)*

**Comment by aledj2** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[code/PrimerDB/ImportPrimer.py, line 77 at r1](https://reviewable.io:443/reviews/woook/moka-fe/365#-KzdQWKF1jOzzbcLPIYK:-Kzdfa-_Uv3hu5vSi6ro:b-e5whnr) ([raw file](https://github.com/woook/moka-fe/blob/985a30b98a6f652ca9a18e5ff1d37d72c9b967a5/code/PrimerDB/ImportPrimer.py#L77)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

FYI according to PEP8 you're not meant to be have whitespace immediately before a comma or colon, just a single whitsepace after. See https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements
</blockquote></details>

will change

---

*[code/PrimerDB/ImportPrimer.py, line 120 at r1](https://reviewable.io:443/reviews/woook/moka-fe/365#-KzdTfu8b3EXsOu89xnS:-KzdeMllb47qxqvzKl_o:bvvmz3v) ([raw file](https://github.com/woook/moka-fe/blob/985a30b98a6f652ca9a18e5ff1d37d72c9b967a5/code/PrimerDB/ImportPrimer.py#L120)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

FYI Doesn't really matter but I don't think you need to put the field names in quotes in an SQL statement do you? Again doesn't really matter but couldn't you just use double quotes for the values rather than backslash escaped single quotes? I think that might make it look slightly neater, avoids having to have strings like `'\',\'' \` on the line below
</blockquote></details>

column names need to be in double quotes because of use of reserved words, (start and stop - although these have been renamed and I think status). The values do need to be in single quotations because SQL thinks double quotes are for columns.

---

*[code/PrimerDB/ImportPrimerConfig.py, line 2 at r1](https://reviewable.io:443/reviews/woook/moka-fe/365#-KzdXdKXT2TQ3yjWhbr0:-KzdfSayKIuNkWUif6RJ:b-asoy15) ([raw file](https://github.com/woook/moka-fe/blob/985a30b98a6f652ca9a18e5ff1d37d72c9b967a5/code/PrimerDB/ImportPrimerConfig.py#L2)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

FYI I think you could also just add r in front of the string to avoid having to escape every backslash i.e. `r"\\gstt.local\shared\Genetics\DNA LAB\Primers\MokaPrimerDatabase\primer_designs"`
</blockquote></details>

that's good. will change this

---

*[forms/61001_PrimerDB_dashboard, line 58 at r1](https://reviewable.io:443/reviews/woook/moka-fe/365#-KzdZHU6fx6rOWGh9oeq:-KzdfYiNSTzEhu97yPcK:b-e5whnr) ([raw file](https://github.com/woook/moka-fe/blob/985a30b98a6f652ca9a18e5ff1d37d72c9b967a5/forms/61001_PrimerDB_dashboard#L58)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

The comment here and below say 'open form' but the command below is actually closing the form.
</blockquote></details>

will change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/365)*

**Comment by andyb3** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/365#-:-Kzdmep4CDK0b0ZrngCx:bnfp4nl)*

**Pull request merged**
