### PR TITLE
Updated script so fe_files don't need to be moved to subfolders

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/441)

### CODE REVIEW

**Comment by aledj2** [comment]
+@aledj2 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/441#-:-L46WPF4X6mxeVdo0KXq:bweg3f8)*

**Comment by aledj2** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[code/hyb_qc_import/hyb_qc_import.py, line 2 at r1](https://reviewable.io:443/reviews/woook/moka-fe/441#-L46XlHElWeyzG3CqtGa:-L46XlHElWeyzG3CqtGb:b5u1ncc) ([raw file](https://github.com/woook/moka-fe/blob/e9a6ddd78fe2f7da1aea3cfccf98857a84678cb8/code/hyb_qc_import/hyb_qc_import.py#L2)):*
> ```Python
> """
> v1.0 - AB 2018/01/18
> ```

new version?

---

*[code/hyb_qc_import/hyb_qc_import.py, line 54 at r1](https://reviewable.io:443/reviews/woook/moka-fe/441#-L46XAoRZASjUQeccpH8:-L46XAoRZASjUQeccpH9:bfxmilp) ([raw file](https://github.com/woook/moka-fe/blob/e9a6ddd78fe2f7da1aea3cfccf98857a84678cb8/code/hyb_qc_import/hyb_qc_import.py#L54)):*
> ```Python
> class FEParser(object):
>     """
>     Parses all fe_files in a directory and inserts the QC records into Moka. Takes a directory as argument.
> ```

guessing it now has >1 input?

---

*[code/hyb_qc_import/hyb_qc_import.py, line 79 at r1](https://reviewable.io:443/reviews/woook/moka-fe/441#-L46X3JvWOgzuIJd7vlF:-L46X3JvWOgzuIJd7vlG:bjsscs3) ([raw file](https://github.com/woook/moka-fe/blob/e9a6ddd78fe2f7da1aea3cfccf98857a84678cb8/code/hyb_qc_import/hyb_qc_import.py#L79)):*
> ```Python
>         self.all_QC_metrics = []
>         # Create connection to Moka
>         self.cnxn = pyodbc.connect('DRIVER={SQL Server}; SERVER=GSTTV-MOKA; DATABASE=devdatabase;', autocommit=True)
> ```

still devdatabase

---

*[code/hyb_qc_import/hyb_qc_import.py, line 150 at r1](https://reviewable.io:443/reviews/woook/moka-fe/441#-L46Y_tYkNgf3Igv4680:-L46Y_tYkNgf3Igv4681:b-351f3q) ([raw file](https://github.com/woook/moka-fe/blob/e9a6ddd78fe2f7da1aea3cfccf98857a84678cb8/code/hyb_qc_import/hyb_qc_import.py#L150)):*
> ```Python
>                     elif line_num == 2:
>                         # Capture barcode/subbarray field, (which contains the barcode and subarray number in format: barcode_group_id 
>                         # e.g. subarray 8 for barcode 12345678 would be: 12345678_2_4)
> ```

is this different to the file name? which I think would be 12345678_2_2_4?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/441)*

**Comment by aledj2** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/441)*

**Comment by andyb3** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[code/hyb_qc_import/hyb_qc_import.py, line 2 at r1](https://reviewable.io:443/reviews/woook/moka-fe/441#-L46XlHElWeyzG3CqtGa:-L46nbBYM66pvnfIbLId:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/e9a6ddd78fe2f7da1aea3cfccf98857a84678cb8/code/hyb_qc_import/hyb_qc_import.py#L2)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

new version?
</blockquote></details>

Done.

---

*[code/hyb_qc_import/hyb_qc_import.py, line 54 at r1](https://reviewable.io:443/reviews/woook/moka-fe/441#-L46XAoRZASjUQeccpH8:-L46nbsBLKExnj2hxsoR:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/e9a6ddd78fe2f7da1aea3cfccf98857a84678cb8/code/hyb_qc_import/hyb_qc_import.py#L54)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

guessing it now has >1 input?
</blockquote></details>

Done.

---

*[code/hyb_qc_import/hyb_qc_import.py, line 79 at r1](https://reviewable.io:443/reviews/woook/moka-fe/441#-L46X3JvWOgzuIJd7vlF:-L46ncLDFAInBlpU0Qoq:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/e9a6ddd78fe2f7da1aea3cfccf98857a84678cb8/code/hyb_qc_import/hyb_qc_import.py#L79)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

still devdatabase
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/441)*

**Comment by andyb3** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[code/hyb_qc_import/hyb_qc_import.py, line 150 at r1](https://reviewable.io:443/reviews/woook/moka-fe/441#-L46Y_tYkNgf3Igv4680:-L46owUrLKMctLRDPt8J:bkdbwnu) ([raw file](https://github.com/woook/moka-fe/blob/e9a6ddd78fe2f7da1aea3cfccf98857a84678cb8/code/hyb_qc_import/hyb_qc_import.py#L150)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is this different to the file name? which I think would be 12345678_2_2_4?
</blockquote></details>

The filename for this example would be `12345678_S01_Guys121919_CGH_1100_Jul11_2_2_4.txt`. Everything after the barcode and before the last 2 numbers is generic for every file.
I realised this comment doesn't make much sense anymore because I stopped referring to groups and ids elsewhere in script, so I have updated it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/441)*

**Comment by aledj2** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/441#-:-L476SwpPCLXZ7pfqM81:bnfp4nl)*

**Comment by aledj2** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/441)*

**Pull request merged**
