### PR TITLE
Create 88005 Insert_patients

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/456)

### CODE REVIEW

**Comment by andyb3** [comment]
+@andyb3 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456#-:-L5xHgtnVk5FYA9DB0Fa:bxccsfn)*

**Comment by andyb3** [comment]
Could the name of this be updated to something like `88005 GeL_Insert_patients` to differentiate from other forms?

---

Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[forms/88005 Insert_patients, line 14 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xOjrtyLvkZEUIEzR2:-L5xOjrtyLvkZEUIEzR3:b-1sgz78) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L14)):*
> ```
>     If Me![ListPatientFound].ListCount = 0 Then
>     ' display a message box saying there were no records identified in GW
>     msga = MsgBox("No records in Geneworks matching that family ID", 0, "No records found")
> ```

FYI you don't need to assign this to a variable. And the parentheses aren't required. i.e this would also work
`MsgBox "No records in Geneworks matching that family ID", 0, "No records found"`

---

*[forms/88005 Insert_patients, line 22 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xPPq6-YSv_eqdvpbl:-L5xPPq6-YSv_eqdvpbm:bl83f4c) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L22)):*
> ```
> Private Sub Form_Open(Cancel As Integer)
>     ' when the form opens set the focus in the box to enter the family id
>     Me![txFamilyTrustID].SetFocus
> ```

I don't think you should need to do this if you have set the tab order for the form.

---

*[forms/88005 Insert_patients, line 39 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xQBxsIHbHTrY_emnF:-L5xQBxsIHbHTrY_emnG:b-tqofez) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L39)):*
> ```
>     Dim internal_patient_id As String
>     Dim strAddPatientSQL As String
>     Dim strAddNGSTest As String
> ```

Could the variable names be updated to use a more consistent style?

---

*[forms/88005 Insert_patients, line 62 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xRtmRyD3F0Kveq_q6:-L5xRtmRyD3F0Kveq_q7:b-ifhima) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L62)):*
> ```
>     
>     ' Test that a patient has been selected
>     If Not IsNull(Me.ListPatientFound.Value) Then
> ```

Could this be moved to the start of this sub so that the query above is not executed if a patient hasn't been selected?

---

*[forms/88005 Insert_patients, line 66 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xTAuK7om2nfTSt4u5:-L5xTAuK7om2nfTSt4u6:b37ehno) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L66)):*
> ```
>         If moka_patients.RecordCount = 0 Then
>             ' insert to moka
>             strAddPatientSQL = "INSERT INTO Patients(PatientID, s_StatusOverall, MokaCreated, MokaCreatedBy, MokaCreatedPC, NHSNumber, BookinLastname, BookinFirstName, BookinDoB, BookinCreatedBy, BookinCreatedDate, BookinSex) SELECT '" & Me.ListPatientFound.Value & "', 1202218839, now(),'" & usr & "','" & cmp & "', dbo_patientlinked.NHSNo, dbo_patientlinked.LastName, dbo_patientlinked.FirstName, dbo_patientlinked.DOB, dbo_patientlinked.CreatedByID, dbo_patientlinked.CreatedDate, dbo_patientlinked.Gender from dbo_patientlinked where patienttrustid = '" & Me.ListPatientFound.Value & "'"
> ```

This line is rather long. Could you add some breaks in?

---

*[forms/88005 Insert_patients, line 67 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xTUoQZHJaJShjrqxq:-L5xTUoROOOlptROWT1_:b-b1oiy7) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L67)):*
> ```
>             ' insert to moka
>             strAddPatientSQL = "INSERT INTO Patients(PatientID, s_StatusOverall, MokaCreated, MokaCreatedBy, MokaCreatedPC, NHSNumber, BookinLastname, BookinFirstName, BookinDoB, BookinCreatedBy, BookinCreatedDate, BookinSex) SELECT '" & Me.ListPatientFound.Value & "', 1202218839, now(),'" & usr & "','" & cmp & "', dbo_patientlinked.NHSNo, dbo_patientlinked.LastName, dbo_patientlinked.FirstName, dbo_patientlinked.DOB, dbo_patientlinked.CreatedByID, dbo_patientlinked.CreatedDate, dbo_patientlinked.Gender from dbo_patientlinked where patienttrustid = '" & Me.ListPatientFound.Value & "'"
>             Debug.Print strAddPatientSQL
> ```

Still has debug statement here

---

*[forms/88005 Insert_patients, line 80 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xTmStpu37jDxfm7S_:-L5xTmStpu37jDxfm7Sa:b-dh7epl) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L80)):*
> ```
>         ElseIf moka_patients.RecordCount > 1 Then
>             ' open a message box warning of this
>             'msgbx = MsgBox("Error - more than one records in patients table for PRU " & Me.ListPatientFound.Value, "Error")
> ```

Again don't need to assign this to a variable. `MsgBox "Error - more than one records in patients table for PRU " & Me.ListPatientFound.Value, "Error"` should work fine

---

*[forms/88005 Insert_patients, line 91 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xRZQba7kEr6tu5eVL:-L5xRZQba7kEr6tu5eVM:b20llb4) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L91)):*
> ```
>         ' update status box on form
>         Me.what_has_happened.Value = "Patient record found in Patients table"
>     End If
> ```

This `End If` should be indented

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456#-:-L5xO4KY3iq2WD1iymPE:bbtbz4g)*

**Comment by andyb3** [comment]
Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions.

---

*[forms/88005 Insert_patients, line 96 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xUdC95PAnDlOdY0MZ:-L5xUdCAPmR1PDR9Vte4:b-wjyrdn) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L96)):*
> ```
>     
>     ' Now we have the internal_patient_id  we can insert to the NGSTestTable
>     ' only want to create a ngstest once = need to check if it has already been added - use service and internal patient id
> ```

I'm not sure if service is the best field to use here. Couldn't we use referralID?

---

*[forms/88005 Insert_patients, line 97 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xUyQj4-Vb48ktk9bC:-L5xUyQj4-Vb48ktk9bD:ba0dvqa) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L97)):*
> ```
>     ' Now we have the internal_patient_id  we can insert to the NGSTestTable
>     ' only want to create a ngstest once = need to check if it has already been added - use service and internal patient id
>     strAddNGSTest = "select * from NGSTest where service = 0 and InternalPatientID = " & internal_patient_id
> ```

This variable says AddNGSTest  (and rsAddNGSTest below) but it is actually just a Select statement

---

*[forms/88005 Insert_patients, line 112 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xWOm673ATGiXtj8kc:-L5xWOm673ATGiXtj8kd:b-jkk90r) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L112)):*
> ```
>         Me.what_has_happened.Value = Me.what_has_happened.Value & vbNewLine & "NGStest created"
>     End If
>     Me.what_has_happened.Value = Me.what_has_happened.Value & vbNewLine & "NGStest already present"
> ```

Shouldn't this be in an `ElseIf rsAddNGSTest.RecordCount = 1 Then` block? I would have thought that this line will still execute even if the `If` block above has executed and the `Me.what_has_happened.Value` of `"NGStest created"` will be overwritten with `"NGStest already present"`. Correct me if I'm wrong though!

---

*[forms/88005 Insert_patients, line 116 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xXWHB81G7gyXvGBL9:-L5xXWHB81G7gyXvGBLA:beedjc1) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L116)):*
> ```
>     Me.s88005_subform.Form.RecordSource = "SELECT NGSTest.NGSTestID, Patients.BookinLastName, Patients.BookinFirstName, Patients.BookinSex, Patients.BookinDOB, GELProbandID, IRID, BookBy, BookingAuthorisedByID FROM NGSTest INNER JOIN Patients ON NGSTest.InternalPatientID = Patients.InternalPatientID where Patients.InternalPatientID = " & internal_patient_id
>     ' requery the subform
>     Me.s88005_subform.Requery
> ```

Could you give the subform a more descriptive name? It can just have the same name as the parent form but with the s in front of the number 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456)*

**Comment by andyb3** [comment]
Could you add afterupdate logs in PatientLog and NGSLogMemo for the fields that can be updated by the user (interpretation request id etc.) 

---

Review status: 0 of 1 files reviewed at latest revision, 13 unresolved discussions.

---

*[forms/88005 Insert_patients, line 131 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xZLzAbTt3SZjd8mo5:-L5xZLzAbTt3SZjd8mo6:bgg3hrq) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L131)):*
> ```
>     Me![txFamilyTrustID].SetFocus
> 
> Exit_refresh_form_Click:
> ```

Good use of error handling (something we probably underuse in Moka!). Perhaps you could add similar error handlers to the other subs too? Also could you add in some comments, even though it is pretty obvious what's going on! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456#-:-L5xY483jbzLOzGn3HpG:b5jg0mx)*

**Comment by andyb3** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456)*

**Comment by aledj2** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[forms/88005 Insert_patients, line 39 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xQBxsIHbHTrY_emnF:-L5xtaIueqTxXwSWjuQ6:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L39)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could the variable names be updated to use a more consistent style?
</blockquote></details>

Done.

---

*[forms/88005 Insert_patients, line 62 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xRtmRyD3F0Kveq_q6:-L5xu02JI2tgKJLtNWhj:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L62)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could this be moved to the start of this sub so that the query above is not executed if a patient hasn't been selected?
</blockquote></details>

Done.

---

*[forms/88005 Insert_patients, line 80 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xTmStpu37jDxfm7S_:-L5xutck44pSq4uMzTID:bpxzd8y) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L80)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Again don't need to assign this to a variable. `MsgBox "Error - more than one records in patients table for PRU " & Me.ListPatientFound.Value, "Error"` should work fine
</blockquote></details>

is commented out but have changed in case we do want this msgbox in future

---

*[forms/88005 Insert_patients, line 91 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xRZQba7kEr6tu5eVL:-L5xv-uKU-uT9qkuItmy:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L91)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

This `End If` should be indented
</blockquote></details>

Done.

---

*[forms/88005 Insert_patients, line 96 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xUdC95PAnDlOdY0MZ:-L5xvUAb2X7Kg-5JQh9-:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L96)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

I'm not sure if service is the best field to use here. Couldn't we use referralID?
</blockquote></details>

Done.

---

*[forms/88005 Insert_patients, line 97 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xUyQj4-Vb48ktk9bC:-L5xvZmr2aeC4mFg8bv2:b-6qxiq7) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L97)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

This variable says AddNGSTest  (and rsAddNGSTest below) but it is actually just a Select statement
</blockquote></details>

yea, was being lazy and re-using variables. Will create a new variable.

---

*[forms/88005 Insert_patients, line 131 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xZLzAbTt3SZjd8mo5:-L5xwudjrJE_qHqLaXyL:bit11e9) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L131)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Good use of error handling (something we probably underuse in Moka!). Perhaps you could add similar error handlers to the other subs too? Also could you add in some comments, even though it is pretty obvious what's going on! 
</blockquote></details>

this was made using the code creator! but thank you!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456)*

**Comment by aledj2** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[forms/88005 Insert_patients, line 116 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xXWHB81G7gyXvGBL9:-L5y0KIYUZsK5B_Y-6xn:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L116)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could you give the subform a more descriptive name? It can just have the same name as the parent form but with the s in front of the number 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456)*

**Comment by andyb3** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[forms/88005 Insert_patients, line 80 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xTmStpu37jDxfm7S_:-L5yYqbr2w4bNwPm36GG:b-v4jxyx) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L80)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is commented out but have changed in case we do want this msgbox in future
</blockquote></details>

Oh yeah sorry didnt spot it was commented

---

*[forms/88005 Insert_patients, line 97 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xUyQj4-Vb48ktk9bC:-L5yZ8efmCT2eo2BFoNL:b-878biu) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L97)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

yea, was being lazy and re-using variables. Will create a new variable.
</blockquote></details>

Haha!

---

*[forms/88005 Insert_patients, line 131 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xZLzAbTt3SZjd8mo5:-L5yZgPM_E52B5TupjML:b3n6k19) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L131)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

this was made using the code creator! but thank you!
</blockquote></details>

There's a code creator??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456)*

**Comment by andyb3** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[forms/88005 Insert_patients, line 116 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xXWHB81G7gyXvGBL9:-L5y_OGYRqEO9w-kueGc:b-hl9byy) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005 Insert_patients#L116)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Perhaps we could use GeL as a prefix in the form names to help distinguish these forms from the other NGS ones? e.g. main form could be `88005 GeL_Insert_patients` and the subform could be `s88005_GeL_updateNGSTest`. I always find it hard to find forms in Moka, so a GeL prefix should make it easier hopefully.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456)*

**Comment by andyb3** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[forms/s88005_updateNGSTest, line 63 at r2](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5ybDEWiNbvdUO0hw8S:-L5ybDEWiNbvdUO0hw8T:bc61vd3) ([raw file](https://github.com/woook/moka-fe/blob/7a39aec167775f7105d0db3c3fbed924819be87d/forms/s88005_updateNGSTest#L63)):*
> ```
>     Resume Exit_NGSTestID_DblClick
> End Sub
> ```

Looks good. Is this the form where the user can add the interpretation request ID, Gel ID etc.? If so, could you add in after update events to log in patient log and NGSLogMemo when these fields are updated. (See WES forms for example code, happy to go through this with you)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456)*

**Comment by aledj2** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[forms/88005_GEL_InsertPatient, line 66 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xTAuK7om2nfTSt4u5:-L61Y4wOOwxyPqGy2bGc:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005_GEL_InsertPatient#L66)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

This line is rather long. Could you add some breaks in?
</blockquote></details>

Done.

---

*[forms/88005_GEL_InsertPatient, line 67 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xTUoQZHJaJShjrqxq:-L61Y5pSawOK0x9_XoE5:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005_GEL_InsertPatient#L67)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Still has debug statement here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456)*

**Comment by aledj2** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[forms/88005_GEL_InsertPatient, line 116 at r1](https://reviewable.io:443/reviews/woook/moka-fe/456#-L5xXWHB81G7gyXvGBL9:-L61hK34R7TpF7xlsA7K:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/bc888ce51d94861fec1715219bfdead6cadb2e2d/forms/88005_GEL_InsertPatient#L116)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Perhaps we could use GeL as a prefix in the form names to help distinguish these forms from the other NGS ones? e.g. main form could be `88005 GeL_Insert_patients` and the subform could be `s88005_GeL_updateNGSTest`. I always find it hard to find forms in Moka, so a GeL prefix should make it easier hopefully.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456)*

**Comment by andyb3** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/456#-:-L61j2vMaFmA9BonLwUu:bnfp4nl)*

**Pull request merged**
