### PR TITLE
Gel fixes

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/462)

### CODE REVIEW

**Comment by aledj2** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[forms/88005_GEL_InsertPatient, line 141 at r1](https://reviewable.io:443/reviews/woook/moka-fe/462#-L6GneQVvQ6-Fx6h7LKK:-L6GneQVvQ6-Fx6h7LKL:b-2ykhq6) ([raw file](https://github.com/woook/moka-fe/blob/e977f6c48cc41bc200c973b9604e9d38106bdd33/forms/88005_GEL_InsertPatient#L141)):*
> ```
>         rsAddNGSTest.Open "SELECT @@identity", CurrentProject.Connection, adOpenKeyset
>         ' assign to variable
>         strNSGTestID = rsAddPatient.Fields(0).Value
> ```

the wrong variable is used to capture the identity

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/462)*

**Comment by woook** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/462#-:-L6Gv0MWTGeIUElRU-ZK:bnfp4nl)*

**Comment by woook** [comment]
Have just reviewed r1 -> r2 for forms/88005_GEL_InsertPatient

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/462#-:-L6Gv3yErcCcH8Rb9ow4:b-hbf64w)*

**Comment by aledj2** [comment]
revision 1 approved, with one comment raised

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/462#-:-L6Gv60nWijpDgn5lyE9:b6n8n5f)*

**Comment by aledj2** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/462#-:-L6Gve8DRKR4U7XMvZvH:bnfp4nl)*

**Comment by aledj2** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/462)*

**Pull request merged**
