### PR TITLE
Explicitly state referral ids when filtering samples on WES Dashboard

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/509)

### CODE REVIEW

**Comment by aledj2** [comment]
fixes #474

**Comment by AmyAmelia** [comment]
+@amyamelia 

---







*Comments from [Reviewable](https://reviewable.io/reviews/woook/moka-fe/509#-:-LC9MJ0A75nKrbL7Fv0W:b-z3lu1q)*

**Comment by AmyAmelia** [comment]
*[forms/87020 ExomeLab, line 1 at r1](https://reviewable.io/reviews/woook/moka-fe/509#-LC9StCp1XxvL5K3N4Va:-LC9StCp1XxvL5K3N4Vb:b-x41sbc) ([raw file](https://github.com/woook/moka-fe/blob/6a7e24800a3525fc87cb2bf1c81c9de844619354/forms/87020 ExomeLab#L1)):*
> ```
> Option Compare Database
> ```

FYI: Will need to go through and ensure code is fully commented. Might be best to address as a progressive improvement as form develops.

---


*Comments from [Reviewable](https://reviewable.io/reviews/woook/moka-fe/509)*

**Comment by AmyAmelia** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/woook/moka-fe/509)*

**Comment by aledj2** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[forms/87020 ExomeLab, line 1 at r1](https://reviewable.io/reviews/woook/moka-fe/509#-LC9StCp1XxvL5K3N4Va:-LC9WaZfAKcoE0OzxPBG:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/6a7e24800a3525fc87cb2bf1c81c9de844619354/forms/87020 ExomeLab#L1)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

FYI: Will need to go through and ensure code is fully commented. Might be best to address as a progressive improvement as form develops.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/woook/moka-fe/509)*

**Comment by AmyAmelia** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/woook/moka-fe/509#-:-LC9WmWI2ClX3Rlv2GIX:bnfp4nl)*

**Pull request merged**
