### PR TITLE
Restrict access to approved personnel only.

### LINKED ISSUE #432: Restrict access to Danger Danger
Use logic/ code from WES approval forms to restrict access to Danger Danger form to array scientists.

### PR DESCRIPTION
**Pull request by AmyAmelia**
Restrict access to the Danger Danger page to array duty scientists. Fixes #432 

---
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/454)

### CODE REVIEW

**Comment by aledj2** [comment]
+@aledj2 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[forms/4752 DeletePatientRecords, line 17 at r1](https://reviewable.io:443/reviews/woook/moka-fe/454#-L5tJuUoeVYm3GnY8FwP:-L5tJuUoeVYm3GnY8FwQ:b1mjw4h) ([raw file](https://github.com/woook/moka-fe/blob/dcc90f96d792d3fff8cbfd983c9a636f1f4956fa/forms/4752 DeletePatientRecords#L17)):*
> ```
> 
> ' Validate that user is authorised. Display alert if not authorised.
> If rsUSR!Authoriser <> 1 And rsUSR!Authoriser <> 4 Then
> ```

should this be AND or OR?
could this be in the sql eg select * from checker where authoriser in (1,4) and checker.username = usr
and then just ensure the recordset.RecordCount != 0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/454#-:-L5tKW32NXN__3hxTu21:bweg3f8)*

**Comment by aledj2** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[forms/4752 DeletePatientRecords, line 5 at r1](https://reviewable.io:443/reviews/woook/moka-fe/454#-L5tKkFW4kBZJcKM3y2c:-L5tKkFW4kBZJcKM3y2d:b-lfr5td) ([raw file](https://github.com/woook/moka-fe/blob/dcc90f96d792d3fff8cbfd983c9a636f1f4956fa/forms/4752 DeletePatientRecords#L5)):*
> ```
> Private Sub Form_Open(Cancel As Integer)
> ' Add in check so that only approved users may access this Danger Danger form
> Dim rsUSR As dao.Recordset
> ```

this is different to some of the recent recordset code that I've seen eg;
Dim rsUSR As ADODB.Recordset
Set rsUSR= New ADODB.Recordset

---

*[forms/4752 DeletePatientRecords, line 8 at r1](https://reviewable.io:443/reviews/woook/moka-fe/454#-L5tK_0TbjoGigRlzV-D:-L5tK_0TbjoGigRlzV-E:b2lym6j) ([raw file](https://github.com/woook/moka-fe/blob/dcc90f96d792d3fff8cbfd983c9a636f1f4956fa/forms/4752 DeletePatientRecords#L8)):*
> ```
> Dim usr As String
> 
> ' Access granted to Arry duty scientists (Checker:Authoriser Col = 4) and Binfx Adimins (Checker:Authoriser Col = 1)
> ```

array and binfx adimins

---

*[forms/4752 DeletePatientRecords, line 14 at r1](https://reviewable.io:443/reviews/woook/moka-fe/454#-L5tKygMRW9Vn4MFCQ68:-L5tKygMRW9Vn4MFCQ69:bo7hy51) ([raw file](https://github.com/woook/moka-fe/blob/dcc90f96d792d3fff8cbfd983c9a636f1f4956fa/forms/4752 DeletePatientRecords#L14)):*
> ```
> strUSRSQL = "SELECT Checker.Name, Checker.Authoriser FROM Checker WHERE Checker.Username = '" + usr + "'"
> Set db = CurrentDb
> Set rsUSR = db.OpenRecordset(strUSRSQL, dbOpenDynaset, dbSeeChanges)
> ```

This is also different to what I've seen elsewehere:
rsUSR.Open strUSRSQL, CurrentProject.Connection, adOpenKeyset

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/454)*

**Comment by AmyAmelia** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[forms/4752 DeletePatientRecords, line 5 at r1](https://reviewable.io:443/reviews/woook/moka-fe/454#-L5tKkFW4kBZJcKM3y2c:-L5xLc1NPxtbgS1kj6FP:b-jg8v0a) ([raw file](https://github.com/woook/moka-fe/blob/dcc90f96d792d3fff8cbfd983c9a636f1f4956fa/forms/4752 DeletePatientRecords#L5)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

this is different to some of the recent recordset code that I've seen eg;
Dim rsUSR As ADODB.Recordset
Set rsUSR= New ADODB.Recordset
</blockquote></details>

DAO and ADODB essentially do the same thing, but DAO is often less wordy whilst ADODB is better for tapping into SQL Server data. As the Data source for this form  is from one table dao is sufficient.  https://accessexperts.com/blog/2013/04/09/dao-or-adodb-which-one-should-you-use-and-when/

---

*[forms/4752 DeletePatientRecords, line 14 at r1](https://reviewable.io:443/reviews/woook/moka-fe/454#-L5tKygMRW9Vn4MFCQ68:-L5xMoE9CEgh85efOYY7:b-txtf5v) ([raw file](https://github.com/woook/moka-fe/blob/dcc90f96d792d3fff8cbfd983c9a636f1f4956fa/forms/4752 DeletePatientRecords#L14)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

This is also different to what I've seen elsewehere:
rsUSR.Open strUSRSQL, CurrentProject.Connection, adOpenKeyset
</blockquote></details>

See above. 

---

*[forms/4752 DeletePatientRecords, line 17 at r1](https://reviewable.io:443/reviews/woook/moka-fe/454#-L5tJuUoeVYm3GnY8FwP:-L5xMrCzyI8Q8AJtRuQL:bxaocyx) ([raw file](https://github.com/woook/moka-fe/blob/dcc90f96d792d3fff8cbfd983c9a636f1f4956fa/forms/4752 DeletePatientRecords#L17)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

should this be AND or OR?
could this be in the sql eg select * from checker where authoriser in (1,4) and checker.username = usr
and then just ensure the recordset.RecordCount != 0
</blockquote></details>

It should be AND.
The SQL could work and be an option of future development. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/454)*

**Comment by aledj2** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[forms/4752 DeletePatientRecords, line 8 at r1](https://reviewable.io:443/reviews/woook/moka-fe/454#-L5tK_0TbjoGigRlzV-D:-L5xpq80RVLlPKE2PL21:b-h1k6ka) ([raw file](https://github.com/woook/moka-fe/blob/dcc90f96d792d3fff8cbfd983c9a636f1f4956fa/forms/4752 DeletePatientRecords#L8)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

array and binfx adimins
</blockquote></details>

BTW adimins still there - not the end of the world!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/454#-:-L5xqL2VJT0QK44FNMFy:bnfp4nl)*

**Comment by aledj2** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/454)*

**Pull request merged**
