### PR TITLE
100 k booking in

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/504)

### CODE REVIEW

**Comment by andyb3** [comment]
+@andyb3 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/woook/moka-fe/504#-:-LB_mxuo9SChX05ahTa9:bxccsfn)*

**Comment by andyb3** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[forms/88005_GEL_InsertPatient, line 149 at r1](https://reviewable.io/reviews/woook/moka-fe/504#-LB_nPhk5bJO9QOHbnGU:-LB_nPhk5bJO9QOHbnGV:bb2ple7) ([raw file](https://github.com/woook/moka-fe/blob/546d6c97e6efd4c8a87092f7003e9262885cdf29/forms/88005_GEL_InsertPatient#L149)):*
> ```
>     ' populate the subform record source
>     Me.s88005_updateNGSTest.Form.RecordSource = "SELECT Patients.BookinLastName & ' ' & Patients.BookinFirstName AS Name, NGSTest.Check4Date, " & _
>     "NGSTest.NGSTestID, NGSTest.InternalPatientID, NGSTest.GELProbandID, NGSTest.IRID, NGSTest.BookBy, NGSTest.StatusID, NGSTest.ResultCode, NGSTest.ReferralID " & _
> ```

Why has this been changed to use Moka patients table rather than GW? Is it to speed things up?

---

*[forms/s88005_GEL_updateNGSTest, line 74 at r1](https://reviewable.io/reviews/woook/moka-fe/504#-LB_noM20-ppwFGS7zvw:-LB_noM20-ppwFGS7zvx:b6rqlmy) ([raw file](https://github.com/woook/moka-fe/blob/546d6c97e6efd4c8a87092f7003e9262885cdf29/forms/s88005_GEL_updateNGSTest#L74)):*
> ```
> End Sub
> 
> Private Sub Name_DblClick(Cancel As Integer)
> ```

It's obvious but could you add a comment saying what this is doing?

---


*Comments from [Reviewable](https://reviewable.io/reviews/woook/moka-fe/504)*

**Comment by andyb3** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/woook/moka-fe/504)*

**Comment by aledj2** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[forms/88005_GEL_InsertPatient, line 149 at r1](https://reviewable.io/reviews/woook/moka-fe/504#-LB_nPhk5bJO9QOHbnGU:-LB_vadGAkoHD-AroHgk:b-vmmomd) ([raw file](https://github.com/woook/moka-fe/blob/546d6c97e6efd4c8a87092f7003e9262885cdf29/forms/88005_GEL_InsertPatient#L149)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Why has this been changed to use Moka patients table rather than GW? Is it to speed things up?
</blockquote></details>

I think so!

---

*[forms/s88005_GEL_updateNGSTest, line 74 at r1](https://reviewable.io/reviews/woook/moka-fe/504#-LB_noM20-ppwFGS7zvw:-LB_vfGt3CUKBh7DMnZ1:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/546d6c97e6efd4c8a87092f7003e9262885cdf29/forms/s88005_GEL_updateNGSTest#L74)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

It's obvious but could you add a comment saying what this is doing?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/woook/moka-fe/504)*

**Comment by andyb3** [comment]
LGTM

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/woook/moka-fe/504#-:-LBa4BXNATtEs9PIQpTb:bb6ywmx)*

**Pull request merged**
