### PR TITLE
V3.80 win10 bugfixes

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/417)

### CODE REVIEW

**Comment by aledj2** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[modules/Firefox, line 8 at r1](https://reviewable.io:443/reviews/woook/moka-fe/417#-L0Eiih8A16x9OWqeN15:-L0Eiih8A16x9OWqeN16:b6ydzcw) ([raw file](https://github.com/woook/moka-fe/blob/b52a5f60571d3094769c091ad1453ec5b5aeb895/modules/Firefox#L8)):*
> ```
>     'Initially set path of executable to chrome on Windows 10
>     v = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
>     'On XP the path to chrome will not exist, so if it doesn't exist, change to firefox path on XP
> ```

what does Len(Dir(v)) return/test?
(sorry)

---

*[modules/Firefox, line 13 at r1](https://reviewable.io:443/reviews/woook/moka-fe/417#-L0EiuaPeYDpudPdYa4T:-L0EiuaPeYDpudPdYa4U:b-i612g6) ([raw file](https://github.com/woook/moka-fe/blob/b52a5f60571d3094769c091ad1453ec5b5aeb895/modules/Firefox#L13)):*
> ```
>     End If
>     Set objShell = CreateObject("Wscript.Shell")
>     objShell.Run ("""" & v & """" & " -new-tab " & url)
> ```

why is v now in quotes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/417)*

**Comment by andyb3** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[modules/Firefox, line 8 at r1](https://reviewable.io:443/reviews/woook/moka-fe/417#-L0Eiih8A16x9OWqeN15:-L0EyFqUnID-eB9DWEPe:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/b52a5f60571d3094769c091ad1453ec5b5aeb895/modules/Firefox#L8)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what does Len(Dir(v)) return/test?
(sorry)
</blockquote></details>

Done.

---

*[modules/Firefox, line 13 at r1](https://reviewable.io:443/reviews/woook/moka-fe/417#-L0EiuaPeYDpudPdYa4T:-L0EyHrHvfJE00rVTdRB:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/b52a5f60571d3094769c091ad1453ec5b5aeb895/modules/Firefox#L13)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

why is v now in quotes?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/417)*

**Comment by aledj2** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/417#-:-L0F-Dozt9rGLCzYT633:bnfp4nl)*

**Comment by aledj2** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/417)*

**Pull request merged**
