### PR TITLE
Feature requests wes coverage

### PR DESCRIPTION
**Pull request by AmyAmelia**
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/455)

### CODE REVIEW

**Comment by aledj2** [comment]
+@aledj2 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/455#-:-L5tDRx3M35hH9ZI9xPt:bweg3f8)*

**Comment by aledj2** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[forms/s0901_NGSCoveragePopup, line 28 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tDhVaj7eZzXD-mTPE:-L5tDhVaj7eZzXD-mTPF:bahssby) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L28)):*
> ```
> Dim yellow As Long
> ' set background colour as veriable using RGB
> white = RGB(255, 255, 255)
> ```

shouldn't white also be defined?

---

*[forms/s0901_NGSCoveragePopup, line 60 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tERJyzH2FoBuE61uj:-L5tERJyzH2FoBuE61uk:b-wqq0dz) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L60)):*
> Please ensure PRU, DNA, NGS Test ID are correct
Is this warning message useful?( is correct the best wording?)

---

*[forms/s0901_NGSCoveragePopup, line 90 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tEpj-rTrXN0r3RTwN:-L5tEpj0fdF91gRg1yaa:bacvfx6) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L90)):*
> use the
used to?

---

*[forms/s0901_NGSCoveragePopup, line 106 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tFnoBoyPEn56KDB0t:-L5tFnoBoyPEn56KDB0u:b-5pp73a) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L106)):*
> ```
>     CovFilename = Dir(rptPath) 'Returns recordset of each matching filename
>     dest_tally = 0
>     Do While CovFilename <> "" 'Loop until no more files, counting any files matching.
> ```

won't this only loop through the first file? won't the below work?
 do while covfilename
 tally=tally+1
loop

---

*[forms/s0901_NGSCoveragePopup, line 170 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tHFWGVtnKE32ibk0N:-L5tHFWGVtnKE32ibk0O:b-9yptps) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L170)):*
> rptName = PRU & "." & DNANumber & ".cov.pdf"
>     'Full path for coverage report
are these lines used?

---

*[forms/s0901_NGSCoveragePopup, line 178 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tHASayEMfEz_HiLu6:-L5tHASayEMfEz_HiLu7:b8dtf7n) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L178)):*
> ```
>          origRptPath = holdingDir & temprptName
>          tempRptPath = holdingDir & finalrptName
>         Name origRptPath As tempRptPath
> ```

name renames files?

---

*[forms/s0901_NGSCoveragePopup, line 179 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tH1PvbYdHCcVLDAnA:-L5tH1PvbYdHCcVLDAnB:b-ndr8k0) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L179)):*
> ```
>          tempRptPath = holdingDir & finalrptName
>         Name origRptPath As tempRptPath
>         Print "Hello"
> ```

guess that isn't needed?

---

*[forms/s0901_NGSCoveragePopup, line 185 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tHaihz0vwVBeLGKeR:-L5tHaihz0vwVBeLGKeS:bo4i23e) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L185)):*
> ```
> 
>     ' Loop through coverage reports in the holding area
>     tempCovFilename = Dir(tempRptPath) 'Returns recordset of each matching filename
> ```

can't use the below to avoid looping?
 If FileExists(tempreppath) Then
  do something
 End If

---

*[forms/s0901_NGSCoveragePopup, line 188 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tI16jbZynDEu6KZWh:-L5tI16jbZynDEu6KZWi:bf0poq6) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L188)):*
> ```
>     hold_tally = 0
>     Do While tempCovFilename <> "" 'Loop until no more files counting matching files.
>         hold_tally = tally + 1
> ```

different variable is being used to count

---

*[forms/s0901_NGSCoveragePopup, line 202 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tIEc0WTJI_5o6okOO:-L5tIEc0WTJI_5o6okOP:b9l5f7j) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L202)):*
> ```
>     If dest_tally > 0 Then 'remove existing coverage report before replacing with new coverage report
>         'Debug.Print rptPath
>         Kill rptPath
> ```

does this delete the file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/455)*

**Comment by aledj2** [comment]
Reviewed 1 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/455)*

**Comment by AmyAmelia** [comment]
*[forms/s0901_NGSCoveragePopup, line 178 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tHASayEMfEz_HiLu6:-L5xInKdgvwN0BiGxBPV:by92dac) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L178)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

name renames files?
</blockquote></details>

Yes, its a vba function, 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/455)*

**Comment by AmyAmelia** [comment]
*[forms/s0901_NGSCoveragePopup, line 106 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tFnoBoyPEn56KDB0t:-L5xJxNPVdb6g37bHuR3:b-hg7blk) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L106)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

won't this only loop through the first file? won't the below work?
 do while covfilename
 tally=tally+1
loop
</blockquote></details>

the CovFilename = Dir 'Moves to next filename in record is what moves the loop to the next record. It gets stuck otherwise. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/455)*

**Comment by AmyAmelia** [comment]
Review status: 2 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[forms/s0901_NGSCoveragePopup, line 106 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tFnoBoyPEn56KDB0t:-L5xQNZvEqzZvA6Trq34:b-ohsbm8) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L106)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

the CovFilename = Dir 'Moves to next filename in record is what moves the loop to the next record. It gets stuck otherwise. 
</blockquote></details>

(This was taken from the import vcf code)

---

*[forms/s0901_NGSCoveragePopup, line 185 at r1](https://reviewable.io:443/reviews/woook/moka-fe/455#-L5tHaihz0vwVBeLGKeR:-L5xTS4CznkeL1ek-56X:b-1jtfhp) ([raw file](https://github.com/woook/moka-fe/blob/3abc1966c613938d1c586d3d02a5e032e309c3da/forms/s0901_NGSCoveragePopup#L185)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can't use the below to avoid looping?
 If FileExists(tempreppath) Then
  do something
 End If
</blockquote></details>

http://www.vbforums.com/showthread.php?375567-RESOLVED-FileExists-is-it-not-a-function 

Re: FileExists is it not a function?
Exists, but is part of Miscrosoft Scripting Runtime, You must add a reference to the library and create the File System Object.

But it would be much easier doing like this:
VB Code:
If Dir("C:\LLMWIN\BATCH\LABEL.BCH") <> VbNullString Then
    Kill "C:\LLMWIN\BATCH\LABEL.BCH"
End If

I have followed and tested the 'easy option' 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/455)*

**Comment by aledj2** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/455#-:-L5y1jkxj-3Lh4Wp_gXG:bnfp4nl)*

**Pull request merged**
