### PR TITLE
Create gel_cover_report.py

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/457)

### CODE REVIEW

**Comment by aledj2** [comment]
Looks good to me except for the two minor things in the code. Tested it from the moka form and it works.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[code/100K/gel_cover_report.py, line 64 at r1](https://reviewable.io:443/reviews/woook/moka-fe/457#-L5yMq9mWvTTte591DfK:-L5yMq9mWvTTte591DfL:b83on67) ([raw file](https://github.com/woook/moka-fe/blob/b8e8887431f3afbf19fce5e4eb3bbb6329f62793/code/100K/gel_cover_report.py#L64)):*
> ```Python
>     # If there is a missing record in an inner joined table, e.g. no clinician address or title, no results will be returned from query.
>     # Check a row has been returned and raise error if not.
>     assert row, 'No results returned from Moka query for NGSTestID {ngs_test_id}. Check there are records in all inner joined tables.'.format(ngs_test_id=ngs_test_id)
> ```

FYI - happy to keep this here, and I might be wrong but do assert statements include a traceback error? Sometimes I don't find that useful, and an make an error message look more complicated than it it. would a print statement and a exit statement be better?

---

*[code/100K/gel_cover_report.py, line 136 at r1](https://reviewable.io:443/reviews/woook/moka-fe/457#-L5yL6Ekq3_cl4AgRbXL:-L5yL6El4ZVwej1K42U-:b-1dsfjk) ([raw file](https://github.com/woook/moka-fe/blob/b8e8887431f3afbf19fce5e4eb3bbb6329f62793/code/100K/gel_cover_report.py#L136)):*
> ```Python
>                 ir_id=demographics['IRID']
>                 )
>     print type(demographics['date_reported'])
> ```

don't think we need this any more

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/457#-:-L5yMiib4JvBwaG1ryko:b-41fu80)*

**Comment by aledj2** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[code/100K/gel_cover_report.py, line 132 at r1](https://reviewable.io:443/reviews/woook/moka-fe/457#-L5yOG9bUylTdznsAJcD:-L5yOG9bUylTdznsAJcE:b-1739or) ([raw file](https://github.com/woook/moka-fe/blob/b8e8887431f3afbf19fce5e4eb3bbb6329f62793/code/100K/gel_cover_report.py#L132)):*
> ```Python
>     g.create_cover_pdf(demographics, r'\\gstt.local\apps\Moka\Files\Software\100K\gel_cover_report_template.html')
>     # Specify the path to the original GeL report, based on the GeL participant ID and the intertpretation request ID retrieved from Moka
>     gel_original_report = r'\\gstt.local\shared\Genetics\Bioinformatics\NGS\GeL\GeL_PDFs_originals\ClinicalReport_{proband_id}_{ir_id}.pdf'.format(
> ```

could we move the reports out of the NGS folder to S:\Genetics\Bioinformatics\GeL\...

Maybe also rename the folders to 'downloaded pdfs' or 'technical reports' and 'reports to send'? Again happy to stay as is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/457)*

**Comment by andyb3** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[code/100K/gel_cover_report.py, line 64 at r1](https://reviewable.io:443/reviews/woook/moka-fe/457#-L5yMq9mWvTTte591DfK:-L5yVFRQcS03TqdYdW2z:b-x3q1k6) ([raw file](https://github.com/woook/moka-fe/blob/b8e8887431f3afbf19fce5e4eb3bbb6329f62793/code/100K/gel_cover_report.py#L64)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

FYI - happy to keep this here, and I might be wrong but do assert statements include a traceback error? Sometimes I don't find that useful, and an make an error message look more complicated than it it. would a print statement and a exit statement be better?
</blockquote></details>

Yes assert does print the traceback. Have updated.

---

*[code/100K/gel_cover_report.py, line 132 at r1](https://reviewable.io:443/reviews/woook/moka-fe/457#-L5yOG9bUylTdznsAJcD:-L5yVaWKXqYNM_MlDoMm:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/b8e8887431f3afbf19fce5e4eb3bbb6329f62793/code/100K/gel_cover_report.py#L132)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

could we move the reports out of the NGS folder to S:\Genetics\Bioinformatics\GeL\...

Maybe also rename the folders to 'downloaded pdfs' or 'technical reports' and 'reports to send'? Again happy to stay as is
</blockquote></details>

Done.

---

*[code/100K/gel_cover_report.py, line 136 at r1](https://reviewable.io:443/reviews/woook/moka-fe/457#-L5yL6Ekq3_cl4AgRbXL:-L5yVbaqomn4gC7sakdD:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/b8e8887431f3afbf19fce5e4eb3bbb6329f62793/code/100K/gel_cover_report.py#L136)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

don't think we need this any more
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/457)*

**Comment by aledj2** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/457#-:-L61eWQvx_Dog-_ouA6U:bnfp4nl)*

**Pull request merged**
