### PR TITLE
100 k tracking

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/482)

### CODE REVIEW

**Comment by andyb3** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[forms/88005_GEL_InsertPatient, line 113 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fKBdZ67jvTuoRTauv:-L8fKBdZ67jvTuoRTauw:bjw21m6) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88005_GEL_InsertPatient#L113)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>
>         ' capture the strInternalPatientID ready to insert to NGSTest
>         strInternalPatientID = rsMokaPatients!InternalPatientID
>         'Update patient status to 100K
>         strPatStatus = "UPDATE Patients SET s_StatusOverall = 1202218839 WHERE InternalPatientID = " & strInternalPatientID
>         'Record status update in log
>         strPatLogStatus = "INSERT INTO PatientLog(InternalPatientID, LogEntry, [Date], Login, PCName) VALUES(" & strInternalPatientID & ", 'Patients: Status changed to 100K ',#" + dt + "#,'" + usr + "','" + cmp + "')"
>         DoCmd.SetWarnings False
>         DoCmd.RunSQL strPatLogStatus
>         DoCmd.SetWarnings True
</details>

Could you indent this else block?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[forms/88006_GEL_tracking, line 20 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fLxhM5qEPRADqtDCI:-L8fLxhM5qEPRADqtDCJ:b-ty8jeb) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L20)):*
> 'Private Sub auth_button_Click()
> 'On Error GoTo Err_auth_button_Click
> '    ' define the form to be opened and the link criteria
> '    Dim stDocName As String
> '    Dim stLinkCriteria As String
> '    stDocName = "88004_100K_auth"
> '    ' open the subform as a datasheet
> '    DoCmd.OpenForm stDocName, acFormDS, , stLinkCriteria
> '
> 'Exit_auth_button_Click:
> '    Exit Sub
> '
> 'Err_auth_button_Click:
> '    MsgBox Err.Description
> '    Resume Exit_auth_button_Click
> '
> 'End Sub

Is this not in use anymore? Should it be deleted?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[forms/88006_GEL_tracking, line 39 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fNyXk48pALmjbhYCh:-L8fNyXk48pALmjbhYCi:bmuk3ed) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L39)):*
> ```
> ' if any of the filters for check1-check4 has been selected:
> ' if check1 has been set
> If Len(check1_filter.Column(0)) > 0 Then
> ```

Could you explain what the check1_filter field is? What is in check1_filter.Column(0)?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Review status: 1 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[forms/88006_GEL_tracking, line 39 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fNyXk48pALmjbhYCh:-L8fPgvRBTAJf_4b1EVW:b-yoao3z) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L39)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could you explain what the check1_filter field is? What is in check1_filter.Column(0)?
</blockquote></details>

(Same goes for other filter fields below)

---

*[forms/88006_GEL_tracking, line 62 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fPG_s-dUbTBpptUDp:-L8fPG_s-dUbTBpptUDq:b-fgwxx8) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L62)):*
> ```
>     Else
>         filter_msg = "[Check3ID]=" & check3_filter.Column(0)
>         End If
> ```

This End If is over-indented. Same goes for check3 below

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Review status: 1 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[forms/88006_GEL_tracking, line 82 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fPzmHCiibxUucdCoi:-L8fPzmHCiibxUucdCoj:b-vzac8l) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L82)):*
> ```
>      ' if no other filters have been set add check3 filter
>     Else
>         filter_msg = filter_msg & "[StatusID]=" & status_filter.Column(0)
> ```

Couldn't this just be:
`filter_msg = "[StatusID]=" & status_filter.Column(0)`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Review status: 1 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[forms/88006_GEL_tracking, line 64 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fQNOe4-taB6bC3l8I:-L8fQNOe4-taB6bC3l8J:b-n7td76) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L64)):*
> ```
>         End If
> End If
> ' if the check3 has been set
> ```

check4?

---

*[forms/88006_GEL_tracking, line 80 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fQVqvAKnpRJgmXIwL:-L8fQVqw3g3YJxzW8b57:bkhlvp9) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L80)):*
> ```
>     If Len(filter_msg) > 0 Then
>         filter_msg = filter_msg & " AND [StatusID]=" & status_filter.Column(0)
>      ' if no other filters have been set add check3 filter
> ```

add status filter?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 6 files at r1.
Review status: 2 of 6 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Review status: 2 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[forms/s88004_GEL_auth_list, line 4 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fTyYd39E9iiXy-lfY:-L8fTREL4QHVCZdNo_K4:b-ppq1wy) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88004_GEL_auth_list#L4)):*
> ```
> 
> 
> Private Sub Check4ID_Change()
> ```

Could you mention here that Check4 is the authoriser field?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[forms/s88004_GEL_auth_list, line 43 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fVHTgBp0ogUd94wdR:-L8fVHTh--7f05qqmIJ5:b-6e9zb) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88004_GEL_auth_list#L43)):*
> ```
>         
>     ' change status to complete, setting check4ID, check4Date and status
>     If Me.Status.Column(0) = 4 Then
> ```

Is the status field bound to the NGStest table? If so, you shouldn't need to set the status in query below.

---

*[forms/s88004_GEL_auth_list, line 45 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fVV4q547fdjPiqW3Z:-L8fVV4q547fdjPiqW3_:b-3rxzux) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88004_GEL_auth_list#L45)):*
> ```
>     If Me.Status.Column(0) = 4 Then
>         ' query that sets the check4 info and the status
>         sqlUpdateChecker = "update NGSTEST, checker set ngstest.check4ID = checker.check1ID, ngstest.check4date = #" + dt + "#, NGSTest.statusID = 4 where checker.username = '" + usr + "' and NGSTestID = " & Me.NGSTestID.Value
> ```

Why is the check4ID set to the check1ID? Why is check4date set here and also in the Check4ID_Change()  sub above? Also pedantic but could you change NGSTEST to NGSTest?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Review status: 2 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[forms/s88004_GEL_auth_list, line 55 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fh6-K3J5ItGR7P1Cr:-L8fh6-K3J5ItGR7P1Cs:b7f5g3f) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88004_GEL_auth_list#L55)):*
> ```
>         DoCmd.RunSQL strmemo
>         DoCmd.SetWarnings True
>     ' if status has been changed to complete double clicking will undo this change - setting check4 to null and status back to authorisation
> ```

This says double clicking but all this code seems to be in an AfterUpdate event rather than a click event??

---

*[forms/s88004_GEL_auth_list, line 58 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fhYTb6i91-RVTa4sC:-L8fhYTb6i91-RVTa4sD:b-h7mo60) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88004_GEL_auth_list#L58)):*
> ```
>     Else
>         ' query that empties the check4 info and resets the status
>         sqlUpdateChecker = "update NGSTEST set ngstest.check4ID = NULL, ngstest.check4date = NULL, NGSTest.statusID = " & Me.Status.Column(0) & " where NGSTestID = " & Me.NGSTestID.Value
> ```

Not that it really matters but could you change NGSTEST to NGSTest?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

*[forms/s88006_GEL_samplelist, line 46 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8flPN222IpnmCXK60b:-L8flPN222IpnmCXK60c:bxbglcu) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88006_GEL_samplelist#L46)):*
> ```
> 
> 
> Private Sub PRU_DblClick(Cancel As Integer)
> ```

Could you add a comment to this to say what it's doing (even though it's obvious!)

---

*[forms/s88006_GEL_samplelist, line 57 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8flfDO-ajNSljqF3bw:-L8flfDO-ajNSljqF3bx:b-v7ma31) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88006_GEL_samplelist#L57)):*
> ```
> End Sub
> 
> Private Sub Referral_DblClick(Cancel As Integer)
> ```

Maybe remove this sub as it's probably not all that useful for the GeL stuff? I expect the information in here is already displayed on the main form anyway? 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Review status: 5 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

*[forms/s88009_GEL_negneg_list, line 51 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fupv49Wv90neV9dIx:-L8fupv49Wv90neV9dIy:bb9pelo) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88009_GEL_negneg_list#L51)):*
> ```
>     
>     'Create shell object
>     Dim wsh As Object
> ```

Could this declaration be moved to the top with the others?

---

*[forms/s88009_GEL_negneg_list, line 65 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fuuAPEqlu4AJ3IDxI:-L8fuuAQ59EwhkZAoCxm:bb9pelo) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88009_GEL_negneg_list#L65)):*
> ```
>     'strReport captures stdout and stderr from executing python script (err is redirected to out in cmd)
>     strReport = wshexec.Stdout.readall()
>     Dim pos As Integer
> ```

Could this declaration be moved to the top with the others?

---

*[forms/s88009_GEL_negneg_list, line 76 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fvoSUD0s_YjY0dAzo:-L8fvoSUD0s_YjY0dAzp:b3fcx1d) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88009_GEL_negneg_list#L76)):*
> ```
>     Else
>         'query that sets check1, and updates status
>         sqlStatusUpdate = "Update NGSTest, checker set status = 'Authorisation', ngstest.check1ID = checker.check1ID, ngstest.check1date = #" + dt + "#, NGSTest.statusID = 1202218814 where checker.username = '" + usr + "' and NGSTestID = " & Me.NGSTestID.Value
> ```

Probably just being dumb but I'm not quite sure how this SQL works. Where is the join between NGSTest and Checker defined? I don't get the `checker.check1ID` bit, isn't check1ID a field in the NGSTest table, not the checker table?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by aledj2** [comment]
Review status: 4 of 6 files reviewed at latest revision, 17 unresolved discussions.

---

*[forms/88005_GEL_InsertPatient, line 113 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fKBdZ67jvTuoRTauv:-L8g-0Ww8KHUF2vtVpa9:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88005_GEL_InsertPatient#L113)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

>         ' capture the strInternalPatientID ready to insert to NGSTest
>         strInternalPatientID = rsMokaPatients!InternalPatientID
>         'Update patient status to 100K
>         strPatStatus = "UPDATE Patients SET s_StatusOverall = 1202218839 WHERE InternalPatientID = " & strInternalPatientID
>         'Record status update in log
>         strPatLogStatus = "INSERT INTO PatientLog(InternalPatientID, LogEntry, [Date], Login, PCName) VALUES(" & strInternalPatientID & ", 'Patients: Status changed to 100K ',#" + dt + "#,'" + usr + "','" + cmp + "')"
>         DoCmd.SetWarnings False
>         DoCmd.RunSQL strPatLogStatus
>         DoCmd.SetWarnings True

Could you indent this else block?
</blockquote></details>

Done.

---

*[forms/88006_GEL_tracking, line 20 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fLxhM5qEPRADqtDCI:-L8g-FFNATnv7hrRoxLE:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L20)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

> 'Private Sub auth_button_Click()
> 'On Error GoTo Err_auth_button_Click
> '    ' define the form to be opened and the link criteria
> '    Dim stDocName As String
> '    Dim stLinkCriteria As String
> '    stDocName = "88004_100K_auth"
> '    ' open the subform as a datasheet
> '    DoCmd.OpenForm stDocName, acFormDS, , stLinkCriteria
> '
> 'Exit_auth_button_Click:
> '    Exit Sub
> '
> 'Err_auth_button_Click:
> '    MsgBox Err.Description
> '    Resume Exit_auth_button_Click
> '
> 'End Sub

Is this not in use anymore? Should it be deleted?
</blockquote></details>

Done.

---

*[forms/88006_GEL_tracking, line 39 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fNyXk48pALmjbhYCh:-L8g04Gd0dN1ISdcKB5x:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L39)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

(Same goes for other filter fields below)
</blockquote></details>

Done.

---

*[forms/88006_GEL_tracking, line 62 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fPG_s-dUbTBpptUDp:-L8g03zN95pJIJIusK9n:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L62)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

This End If is over-indented. Same goes for check3 below
</blockquote></details>

Done.

---

*[forms/88006_GEL_tracking, line 64 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fQNOe4-taB6bC3l8I:-L8g03oR-CsI-zi51yQZ:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L64)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

check4?
</blockquote></details>

Done.

---

*[forms/88006_GEL_tracking, line 82 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fPzmHCiibxUucdCoi:-L8g0TbNB47w4utBiCyU:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L82)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Couldn't this just be:
`filter_msg = "[StatusID]=" & status_filter.Column(0)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by aledj2** [comment]
Review status: 2 of 6 files reviewed at latest revision, 17 unresolved discussions.

---

*[forms/88006_GEL_tracking, line 80 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fQVqvAKnpRJgmXIwL:-L8g0uAdD5T31AfD_Jpr:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/88006_GEL_tracking#L80)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

add status filter?
</blockquote></details>

Done.

---

*[forms/s88006_GEL_samplelist, line 46 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8flPN222IpnmCXK60b:-L8g1a9nEuRDvBrPhodA:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88006_GEL_samplelist#L46)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could you add a comment to this to say what it's doing (even though it's obvious!)
</blockquote></details>

Done.

---

*[forms/s88006_GEL_samplelist, line 57 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8flfDO-ajNSljqF3bw:-L8g1am-1AWJWE9WVEV1:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88006_GEL_samplelist#L57)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Maybe remove this sub as it's probably not all that useful for the GeL stuff? I expect the information in here is already displayed on the main form anyway? 
</blockquote></details>

Done.

---

*[forms/s88009_GEL_negneg_list, line 51 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fupv49Wv90neV9dIx:-L8g1wsb1ADS-eEV8jJQ:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88009_GEL_negneg_list#L51)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could this declaration be moved to the top with the others?
</blockquote></details>

Done.

---

*[forms/s88009_GEL_negneg_list, line 65 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fuuAPEqlu4AJ3IDxI:-L8g2228-Vl7jNj6p87u:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88009_GEL_negneg_list#L65)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could this declaration be moved to the top with the others?
</blockquote></details>

Done.

---

*[forms/s88009_GEL_negneg_list, line 76 at r1](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8fvoSUD0s_YjY0dAzo:-L8g287Q5f9RZsRtRxsI:b-tdsdz7) ([raw file](https://github.com/woook/moka-fe/blob/78ba9408ef2c7f99360304d62410a24ed6bcb563/forms/s88009_GEL_negneg_list#L76)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Probably just being dumb but I'm not quite sure how this SQL works. Where is the join between NGSTest and Checker defined? I don't get the `checker.check1ID` bit, isn't check1ID a field in the NGSTest table, not the checker table?
</blockquote></details>

check1ID is the name of the primary key in the checker table. It's also used as the first checker in the NGS Test Table. Also The status = authorisation bit shouldn't be there!!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 2 of 7 files at r2.
Review status: 4 of 9 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 7 files at r2.
Review status: 5 of 10 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 7 files at r2.
Review status: 6 of 10 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Review status: 6 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[queries/s88004_GEL_auth_list, line 3 at r2](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8g5oeV4auUdMt5OpoS:-L8g5oeW1RHr-srzg4n6:b-pgvt4q) ([raw file](https://github.com/woook/moka-fe/blob/05eae214e4e97804729db7c33adf009c0ab26d64/queries/s88004_GEL_auth_list#L3)):*
> ```
> SELECT Checker.Name AS ReferringClinician, NGSTest.GELProbandID AS GELparticipantID, NGSTest.IRID, Patients.BookinSex AS Sex, NGSTest.NGSTestID, NGSTest.Check4Date AS AuthorisedDate, NGSTest.StatusID, NGSTest.InternalPatientID, Patients.PatientID, "https://cipapi.genomicsengland.nhs.uk/interpretationportal/#/participant/" & [NGSTest].[IRID] & "/tiering" AS ReviewVariantsURL, Patients.BookinLastName AS LastName, Patients.BookinFirstName AS FirstName, Patients.BookinDOB AS DOB, NGSTest.Check4ID
> FROM (NGSTest INNER JOIN Patients ON NGSTest.InternalPatientID = Patients.InternalPatientID) LEFT JOIN Checker ON NGSTest.BookBy = Checker.Check1ID
> WHERE (((NGSTest.StatusID)=1202218814) AND ((NGSTest.ReferralID)=1199901218) AND ((NGSTest.ResultCode)=1189679668));
> ```

Is that the result code for negative negatives? Is this form only going to be used for negative negatives?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 7 files at r2.
Review status: 7 of 10 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 7 files at r2, 1 of 1 files at r3.
Review status: 9 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[queries/s88006_List100KSamples, line 4 at r2](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8g7WR_0r1NNlpYrVz-:-L8g7WR_0r1NNlpYrVz0:b-ua3h9r) ([raw file](https://github.com/woook/moka-fe/blob/05eae214e4e97804729db7c33adf009c0ab26d64/queries/s88006_List100KSamples#L4)):*
> ```
> FROM (((((((NGSTest INNER JOIN Patients ON NGSTest.InternalPatientID = Patients.InternalPatientID) LEFT JOIN NGSPanel ON NGSTest.NGSPanelID = NGSPanel.NGSPanelID) LEFT JOIN NGSPanel AS NGSPanel_1 ON NGSTest.NGSPanelID_B = NGSPanel_1.NGSPanelID) INNER JOIN dbo_Patient_table ON Patients.PatientID = dbo_Patient_table.PatientTrustID) INNER JOIN Status AS Status_1 ON Patients.s_StatusOverall = Status_1.StatusID) LEFT JOIN gw_GenderTable ON dbo_Patient_table.GenderID = gw_GenderTable.GenderID) LEFT JOIN NGSPanel AS NGSPanel_2 ON NGSTest.NGSPanelID_C = NGSPanel_2.NGSPanelID) LEFT JOIN Checker ON NGSTest.BookBy = Checker.Check1ID
> WHERE (((NGSTest.ReferralID)=1199901218))
> ORDER BY NGSTest.Priority, NGSTest.DateRequested;
> ```

I think there's a lot of stuff in here that could be removed? e.g. all the NGSPanel stuff because that is only applicable to WES. This would remove some left joins and speed up the query.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by aledj2** [comment]
Review status: 7 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[queries/s88004_GEL_auth_list, line 3 at r2](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8g5oeV4auUdMt5OpoS:-L8gE9Km58kGR8N4RZ_9:b-4pgn7b) ([raw file](https://github.com/woook/moka-fe/blob/05eae214e4e97804729db7c33adf009c0ab26d64/queries/s88004_GEL_auth_list#L3)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Is that the result code for negative negatives? Is this form only going to be used for negative negatives?
</blockquote></details>

yes(to both)

---

*[queries/s88006_List100KSamples, line 4 at r2](https://beta.reviewable.io/reviews/woook/moka-fe/482#-L8g7WR_0r1NNlpYrVz-:-L8gEv-0C2A71bUAX4w7:bnzdcg1) ([raw file](https://github.com/woook/moka-fe/blob/05eae214e4e97804729db7c33adf009c0ab26d64/queries/s88006_List100KSamples#L4)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

I think there's a lot of stuff in here that could be removed? e.g. all the NGSPanel stuff because that is only applicable to WES. This would remove some left joins and speed up the query.
</blockquote></details>

good spot! done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 7 files at r2, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
Reviewed 1 of 3 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482)*

**Comment by andyb3** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/woook/moka-fe/482#-:-L8lcTNG81KeQfqiggaD:bnfp4nl)*

**Pull request merged**
