### PR TITLE
Consumables dev Fixes #182 and #232 

### LINKED ISSUE #182: New report facility in Moka Consumables
I’d like to have some minor additions made to Moka Consumables to help the Oncology Team monitor expired stock.  It would be good to generate a new query (section specific) for active expired stock that would generate a report and allow us to monitor which stock is in use and has expired, and which stock is due to expire in the next 3 months.  It would require some additional data entry on our part with a new tick box alongside each order entry to say when stock has been finished – we would include this as part of our weekly stock monitoring.  There would also be a lot of old stock that would need to be tick-boxed as finished, but this is a one-off job.  This is primarily for the Oncology Team, but could be used by the Array Team too.

### PR DESCRIPTION
**Pull request by Graeme-Smith**
This change is [Reviewable](https://reviewable.io/reviews/woook/moka-fe/473)

### CODE REVIEW

**Comment by andyb3** [comment]
+@andyb3 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/473#-:-L73i-8ssnZENh5khVEF:bxccsfn)*

**Comment by andyb3** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[forms/001_Start, line 83 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73lVQmc5y6UvRk7Dch:-L73lVQnFxpjwd5NYtqz:b-n5jihx) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/001_Start#L83)):*
> ```
> Private Sub Command32_Click()
>     Dim stDocName As String
>     stDocName = "s_expiredConsumables1"
> ```

Normally we only use the `s` prefix for subforms. The main form is given a name with a numbered prefix. By the looks of it the consumables forms seem to start with a `33` so maybe you could change the name of the form to something like`336 ExpiredConsumables`. (Any subforms of this form would then be prefixed with s336_`

---

*[forms/333 BatchTestingRequired SQL, line 3 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73pBk3qSMshkeQcJGT:-L73pBk3qSMshkeQcJGU:bve5vbk) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/333 BatchTestingRequired SQL#L3)):*
> ```
> SELECT Consumable.Consumable, Company.Company, Consumable.CatalogueNo, ConsumableStock.DateOrdered, ConsumableStock.QuantityOrdered, ConsumableStock.LotNo, ConsumableStock.DateReceived, ConsumableBatchTesting.DateTested, ConsumableBatchTesting.SampleTested, ConsumableStock.SectionID, ConsumableBatchTesting.ConsumableBatchTestingID, ConsumableBatchTesting.ConsumableStockID, Consumable.ConsumableID, ConsumableStock.AuthorisedForUseBy
> FROM ((Consumable LEFT JOIN ConsumableStock ON Consumable.ConsumableID = ConsumableStock.ConsumableID) LEFT JOIN ConsumableBatchTesting ON ConsumableStock.ConsumableStockID = ConsumableBatchTesting.ConsumableStockID) LEFT JOIN Company ON Consumable.CompanyID = Company.CompanyID
> WHERE (((ConsumableStock.DateReceived)>#2/7/2012#) AND ((ConsumableBatchTesting.DateTested) Is Null) AND ((ConsumableStock.SectionID)=156))
> ```

Any idea why the date has to be > 2/7/2012? And what does section ID 156 refer to?

---

*[forms/s_expiredConsumables1, line 1 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73nJHAu-CVc87g5Z_Y:-L73nJHAu-CVc87g5Z_Z:b3ak4p3) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/s_expiredConsumables1#L1)):*
> ```
> Option Compare Database
> ```

See comment on `001_start` regarding the naming of this form

---

*[forms/s_expiredConsumables1, line 14 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73oOJ2xignyNxDXQMJ:-L73oOJ2xignyNxDXQMK:bgxvzlh) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/s_expiredConsumables1#L14)):*
> ```
> Private Sub PageHeaderSection_Click()
> 
> End Sub
> ```

It looks like the above two subs don't do anything (top one is commented out and the other one is empty). Could these be deleted?

---

*[forms/s_expiredConsumables1, line 29 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73okzttpc8SrZbt-ZJ:-L73okzul85MEe9Oo_TI:bul7o1m) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/s_expiredConsumables1#L29)):*
> ```
>     Resume Exit_cmdPrintRecord_Click
>     
> End Sub
> ```

Please comment the above sub to explain what's happening

---

*[forms/s_expiredConsumables1, line 31 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73ofEdLdBdWA51bW68:-L73ofEdLdBdWA51bW69:b-nzmxxe) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/s_expiredConsumables1#L31)):*
> ```
> End Sub
> 
> Private Sub Detail_Click()
> ```

Again looks like this sub is empty so please could it be deleted?

---

*[queries/s_expiredConsumables, line 3 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73pUpKO0wa53ldLQ8D:-L73pUpKO0wa53ldLQ8E:bovqvqf) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/queries/s_expiredConsumables#L3)):*
> ```
> SELECT ConsumableStock.ConsumableStockID, ConsumableStock.ConsumableID, ConsumableStock.InternalOrderNo, ConsumableStock.ExternalOrderNo, ConsumableStock.DateOrdered, ConsumableStock.QuantityOrdered, ConsumableStock.LotNo, ConsumableStock.KitLotNo, ConsumableStock.DateReceived, ConsumableStock.ExpiryDate, ConsumableStock.Finished, ConsumableStock.SectionID, ConsumableStock.AuthorisedForUseBy, ConsumableStock.StockUsed, Consumable.Active, Status.Status, Item.Item, Checker.Name, Checker_1.Name, Checker_2.Name, ConsumableStock.StockUsed
> FROM (((((ConsumableStock LEFT JOIN Consumable ON ConsumableStock.ConsumableID = Consumable.ConsumableID) LEFT JOIN Status ON Consumable.Active = Status.StatusID) LEFT JOIN Item ON ConsumableStock.SectionID = Item.ItemID) LEFT JOIN Checker ON ConsumableStock.OrderedFor = Checker.Check1ID) LEFT JOIN Checker AS Checker_1 ON ConsumableStock.OrderedBy = Checker_1.Check1ID) LEFT JOIN Checker AS Checker_2 ON ConsumableStock.AuthorisedForUseBy = Checker_2.Check1ID
> WHERE (((ConsumableStock.ExpiryDate)<DateAdd("m",3,Date())) AND ((Consumable.Active)=1202218774) AND ((ConsumableStock.StockUsed)=False))
> ```

What does `DateAdd("m",3,Date())` do? Is it pulling out everything that is expired or has less than 3 months until expiry?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/473)*

**Comment by Graeme-Smith** [comment]
Reviewed 1 of 1 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[forms/001_Start, line 83 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73lVQmc5y6UvRk7Dch:-L74SrM8xWWO3AyK0Uew:bov3mw2) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/001_Start#L83)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Normally we only use the `s` prefix for subforms. The main form is given a name with a numbered prefix. By the looks of it the consumables forms seem to start with a `33` so maybe you could change the name of the form to something like`336 ExpiredConsumables`. (Any subforms of this form would then be prefixed with s336_`
</blockquote></details>

Changed to 336_expiredConsumables

---

*[forms/333 BatchTestingRequired SQL, line 3 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73pBk3qSMshkeQcJGT:-L7446ewc2f8cBcfixnB:b3ylbk1) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/333 BatchTestingRequired SQL#L3)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Any idea why the date has to be > 2/7/2012? And what does section ID 156 refer to?
</blockquote></details>

Both are from Moka legacy code.  SectionID 156 refers to _"Oncology, probes"_ in the _Item_ lookup table which contains descriptions for many different keys - I assume this is so that the description can be changed in a single table without necessitating alterations to every table using that key.  From talking with Toby Kirby I believe that they only want to return _"Oncology, probes"_ stock in this form.  I think the reason that the query only returns items after 2/7/2012 is because the table  _consumableBatchTesting_ was created about that time. As the code filters on `((ConsumableBatchTesting.DateTested) Is Null)` this is one way to prevent being swamped with data before this date without having to fill in the field for all old stock.

---

*[forms/336 expiredConsumables, line 1 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73nJHAu-CVc87g5Z_Y:-L74UY5qJUZYOL-gh95M:b-896fix) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/336 expiredConsumables#L1)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

See comment on `001_start` regarding the naming of this form
</blockquote></details>

Done.

---

*[forms/336 expiredConsumables, line 14 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73oOJ2xignyNxDXQMJ:-L74_JKPVzX4JWgws3nx:bhofej8) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/336 expiredConsumables#L14)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

It looks like the above two subs don't do anything (top one is commented out and the other one is empty). Could these be deleted?
</blockquote></details>

Deleted

---

*[forms/336 expiredConsumables, line 29 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73okzttpc8SrZbt-ZJ:-L74_LQmZdMJWV_3ZXnm:b9jr4le) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/336 expiredConsumables#L29)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Please comment the above sub to explain what's happening
</blockquote></details>

Deleted - related to  print button in earlier version which has been removed.

---

*[forms/336 expiredConsumables, line 31 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73ofEdLdBdWA51bW68:-L74_MmE069suagvVRLF:bhofej8) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/336 expiredConsumables#L31)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Again looks like this sub is empty so please could it be deleted?
</blockquote></details>

Deleted

---

*[queries/s_expiredConsumables, line 3 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73pUpKO0wa53ldLQ8D:-L742Cdjm4TQz9URGKzX:brp6lnr) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/queries/s_expiredConsumables#L3)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

What does `DateAdd("m",3,Date())` do? Is it pulling out everything that is expired or has less than 3 months until expiry?
</blockquote></details>

As per the requirement from Toby Kirby he wanted to be able to print a list of expired items and also items which will expire in the next 3 months.  I return everything whose expiry date is before 3 months from now.  The form differentiates between the two using conditional formatting - yellow for soon to be expired, red for expired.  The form also sorts records ascending by expiry date.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/473)*

**Comment by Graeme-Smith** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/473)*

**Comment by andyb3** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/473)*

**Comment by andyb3** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/473#-:-L74n_ty7Pv7qkNLPbN-:bnfp4nl)*

**Comment by andyb3** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[forms/001_Start, line 83 at r1](https://reviewable.io:443/reviews/woook/moka-fe/473#-L73lVQmc5y6UvRk7Dch:-L74njt6nBjPOvPOp6mO:bsrfkwe) ([raw file](https://github.com/woook/moka-fe/blob/2d27b3694e2f13490e71e6e16d74d6465a464fd7/forms/001_Start#L83)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Changed to 336_expiredConsumables
</blockquote></details>

Looks good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/473)*

**Comment by Graeme-Smith** [comment]
Reviewed 4 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/woook/moka-fe/473)*

**Pull request merged**
